
# BUILD: docker build -t <image_name> <docker_file_location_folder>
#      example: docker run build -t a4 C:\docker
# RUN: docker run -p 8888:8000 -v <local_machine_folder>:/opendxl -t <image_name>
#      example: docker run -p 8888:8000 -v /c/docker/opendxl:/opendxl -t a4

FROM centos:centos7
MAINTAINER The CentOS Project <cloud-ops@centos.org>

VOLUME ["/opendxl"]

RUN curl https://raw.githubusercontent.com/amolkokje/python_env_setup/master/centos_setup/centos_setup.sh > centos_env_setup.sh
RUN chmod 775 centos_env_setup.sh
RUN ./centos_env_setup.sh | tee -a "centos_env_setup.log"

RUN pip install dxlclient
RUN pip install dxlconsole


EXPOSE 8000

